# Generated by Django 5.1.1 on 2024-10-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='title',
        ),
        migrations.AddField(
            model_name='episode',
            name='episode_number',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='episode',
            name='season_number',
            field=models.DecimalField(decimal_places=1, default='1', max_digits=5),
        ),
    ]
