# Generated by Django 5.1.1 on 2024-10-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_episode_title_episode_episode_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='previews/'),
        ),
    ]
