# Generated by Django 5.1.1 on 2024-10-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_episode_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='preview',
            field=models.ImageField(default=None, upload_to='previews/'),
            preserve_default=False,
        ),
    ]
