# Generated by Django 5.1.1 on 2024-10-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_episode_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='preview',
            field=models.ImageField(null=True, upload_to='previews/'),
        ),
    ]
