# Generated by Django 5.1.1 on 2024-10-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_episode_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='preview'),
        ),
    ]
