# Generated by Django 5.1.1 on 2024-11-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_episode_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.CharField(default='1', max_length=20)),
                ('season_number', models.DecimalField(decimal_places=1, default='1', max_digits=5)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
