# Generated by Django 5.1.1 on 2024-11-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.FileField(blank=True, null=True, upload_to='video/'),
        ),
    ]
